# Generated by Django 5.2.7 on 2025-10-31 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_shippingaddress_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
    ]
